server {
    listen 80;
    server_name planner.remmick.com;

    root /usr/share/nginx/html;
    index Login.html;

    location / {
        try_files $uri $uri/ /Login.html;
    }

    access_log /var/log/nginx/frontend_access.log;
    error_log /var/log/nginx/frontend_error.log;
}


server {
    listen 80;
    server_name api.remmick.com;

    root /var/www/html/Backend/Public;
    index Index.php;

    location / {
        try_files $uri $uri/ /Index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass backend:9000;

        fastcgi_param SCRIPT_FILENAME /var/www/html/Public$fastcgi_script_name;
    }

    access_log /var/log/nginx/backend_access.log;
    error_log /var/log/nginx/backend_error.log;
}